# Используем базовый образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файл requirements.txt в рабочую директорию
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем все файлы из текущей директории в рабочую директорию контейнера
COPY . .

# Устанавливаем переменную окружения для указания, что это приложение
ENV JAVA_OPTS=""

# Указываем команду для запуска бота
CMD ["python", "your_bot_script.py"]
